const states = [
    {
        "st_nm":"Andhra Pradesh",
        "st":"AndhraPradesh",
        "lat":"14.7504291",
        "long":"78.57002559",
        "zones": {
                "Kurnool" : "Red Zone",
                "Guntur" : "Red Zone",
                "Krishna" : "Red Zone",
                "Chittoor" : "Red Zone",
                "Sri Potti Sriramulu Nellore" : "Red Zone",
                "West Godavari" : "Orange Zone",
                "Y.s.r" : "Orange Zone",
                "Anantapur" : "Orange Zone",
                "Prakasam" : "Orange Zone",
                "East Godavari" : "Orange Zone",
                "Srikakulam" : "Orange Zone",
                "Visakhapatnam" : "Orange Zone",
                "Vizianagaram" : "Green Zone"
            }
    },
    {
        "st_nm":"Arunanchal Pradesh",
        "st":"ArunanchalPradesh",
        "lat":"27.10039878",
        "long":"93.61660071",
        "zones" : {
                "West Kameng" : "Green Zone",
                "East Kameng" : "Green Zone",
                "Papum Pare" : "Green Zone",
                "Kurung Kumey" : "Green Zone",
                "Kra Daadi" : "Green Zone",
                "Lower Subansiri" : "Green Zone",
                "Upper Subansiri" : "Green Zone",
                "West Siang" : "Green Zone",
                "East Siang" : "Green Zone",
                "Siang" : "Green Zone",
                "Upper Siang" : "Green Zone",
                "Lower Siang" : "Green Zone",
                "Lower Dibang Valley" : "Green Zone",
                "Dibang Valley" : "Green Zone",
                "Anjaw" : "Green Zone",
                "Lohit" : "Green Zone",
                "Namsai" : "Green Zone",
                "Changlang" : "Green Zone",
                "Tirap" : "Green Zone",
                "Longding" :"Green Zone"
        }
    },
    {
        "st_nm":"Assam",
        "st":"Assam",
        "lat":"26.7499809",
        "long":"94.21666744",
        "zones" : {
            "Baksa" : "Green Zone",
            "Barpeta" : "Green Zone",
            "Biswanath": "Green Zone",
            "Bongaigaon": "Green Zone",
            "Cachar": "Green Zone",
            "Charaideo": "Green Zone",
            "Chirang": "Green Zone",
            "Darrang": "Green Zone",
            "Dhemaji": "Green Zone",
            "Dhubri" : "Orange Zone",
            "Dibrugarh": "Green Zone",
            "Goalpara" : "Orange Zone",
            "Golaghat": "Green Zone",
            "Hailakandi": "Green Zone",
            "Hojai": "Green Zone",
            "Jorhat": "Green Zone",
            "Kamrup Metropolitan": "Green Zone",
            "Kamrup": "Green Zone",
            "Karbi Anglong": "Green Zone",
            "Karimganj": "Green Zone",
            "Kokrajhar": "Green Zone",
            "Lakhimpur": "Green Zone",
            "Majuli": "Green Zone",
            "Marigaon" : "Orange Zone",
            "Nagaon": "Green Zone",
            "Nalbari": "Green Zone",
            "Dima Hasao": "Green Zone",
            "Sivasagar": "Green Zone",
            "Sonitpur": "Green Zone",
            // "South SalmaraMankachar": "Green Zone",
            "Tinsukia": "Green Zone",
            "Udalguri": "Green Zone",
            // "West Karbi Anglong": "Green Zone"
        }
    },
    {
        "st_nm":"Bihar",
        "st":"Bihar",
        "lat":"25.78541445",
        "long":"87.4799727",
        "zones" : {
            "Araria": "Green Zone",
            "Arwal": "Orange Zone",
            "Aurangabad": "Orange Zone",
            "Banka": "Orange Zone",
            "Begusarai": "Orange Zone",
            "Bhagalpur": "Orange Zone",
            "Bhojpur": "Orange Zone",
            "Buxar" : "Red Zone",
            "Darbhanga": "Orange Zone",
            // "East Champaran (Motihari)",
            "Gaya" : "Red Zone",
            "Gopalganj": "Orange Zone",
            "Jamui": "Green Zone",
            "Jehanabad": "Orange Zone",
            "Kaimur (Bhabua)": "Orange Zone",
            "Katihar": "Green Zone",
            "Khagaria": "Green Zone",
            "Kishanganj": "Green Zone",
            "Lakhisarai": "Orange Zone",
            "Madhepura": "Orange Zone",
            "Madhubani": "Orange Zone",
            "Munger (Monghyr)" : "Red Zone",
            "Muzaffarpur": "Green Zone",
            "Nalanda" : "Orange Zone",
            "Nawada": "Orange Zone",
            "Patna" : "Red Zone",
            "Purnia (Purnea)": "Orange Zone",
            "Rohtas" : "Red Zone",
            "Saharsa": "Green Zone",
            "Samastipur": "Green Zone",
            "Saran": "Orange Zone",
            "Sheikhpura": "Green Zone",
            "Sheohar": "Green Zone",
            "Sitamarhi": "Green Zone",
            "Siwan": "Orange Zone",
            "Supaul": "Green Zone",
            "Vaishali": "Orange Zone",
            "West Champaran": "Green Zone"
        }
    },
    {
        "st_nm":"Chhattisgarh",
        "st":"Chhattisgarh",
        "lat":"22.09042035",
        "long":"82.15998734",
        "zones" : {
            "Balod" : "Green Zone",
            "Baloda Bazar": "Green Zone",
            "Balrampur": "Green Zone",
            "Bastar": "Green Zone",
            "Bemetara": "Green Zone",
            "Bijapur": "Green Zone",
            "Bilaspur": "Green Zone",
            "Dakshin Bastar Dantewada": "Green Zone",
            "Dhamtari": "Green Zone",
            "Durg": "Green Zone",
            "Gariyaband": "Green Zone",
            "Janjgir-Champa": "Green Zone",
            "Jashpur": "Green Zone",
            "Kabeerdham": "Green Zone",
            "Uttar Bastar Kanker": "Green Zone",
            "Kondagaon": "Green Zone",
            "Korba" : "Orange Zone",
            "Koriya": "Green Zone",
            "Mahasamund": "Green Zone",
            // "Mungeli": "Green Zone",
            "Narayanpur": "Green Zone",
            "Raigarh": "Green Zone",
            "Raipur" : "Red Zone",
            "Rajnandgaon": "Green Zone",
            "Sukma": "Green Zone",
            "Surajpur": "Green Zone",
            "Surguja": "Green Zone"
        }
    },
    {
        "st_nm":"Goa",
        "st":"Goa",
        "lat":"15.491997",
        "long":"73.81800065",
        "zones" : {
            "North Goa" : "Green Zone",
            "South Goa" : "Green Zone"
        }
    },
    {
        "st_nm":"Gujarat",
        "st":"Gujarat",
        "lat":"22.2587",
        "long":"71.1924",
        "zones" : {
            "Ahmedabad" : "Red Zone",
            "Amreli": "Green Zone",
            "Anand" : "Red Zone",
            // "Aravalli" : "Red Zone",
            "Banas Kantha" : "Red Zone",
            "Bharuch" : "Orange Zone",
            "Bhavnagar" : "Red Zone",
            // "Botad" : "Orange Zone",
            "Chhota Udepur" : "Orange Zone",
            "Dahod" : "Orange Zone",
            "The Dangs" : "Orange Zone",
            // "Devbhoomi Dwarka": "Green Zone",
            "Gandhinagar" : "Red Zone",
            // "Gir Somnath" : "Orange Zone",
            "Jamnagar" : "Orange Zone",
            "Junagadh": "Green Zone",
            "Kachchh" : "Orange Zone",
            "Kheda" : "Orange Zone",
            "Mahisagar" : "Orange Zone",
            "Mehsana" : "Orange Zone",
            "Morbi" : "Green Zone",
            "Panch Mahals" : "Red Zone",
            "Narmada" : "Orange Zone",
            "Navsari" : "Orange Zone",
            "Patan" : "Orange Zone",
            "Porbandar": "Green Zone",
            "Rajkot" : "Orange Zone",
            "Sabar Kantha" : "Orange Zone",
            "Surat" : "Red Zone",
            "Surendranagar" : "Orange Zone",
            "Tapi" : "Orange Zone",
            "Vadodara" : "Red Zone",
            "Valsad" : "Orange Zone"
        }
    },
    {
        "st_nm":"Haryana",
        "st":"Haryana",
        "lat":"28.45000633",
        "long":"77.01999101",
        "zones" : {
            "Ambala" : "Orange Zone",
            "Bhiwani" : "Orange Zone",
            "Charkhi Dadri" : "Orange Zone",
            "Faridabad" : "Red Zone",
            "Fatehabad" : "Orange Zone",
            "Gurgaon" : "Orange Zone",
            "Hisar" : "Orange Zone",
            "Jhajjar" : "Orange Zone",
            "Jind" : "Orange Zone",
            "Kaithal" : "Orange Zone",
            "Karnal" : "Orange Zone",
            "Kurukshetra" : "Orange Zone",
            "Mahendragarh" : "Green Zone",
            "Mewat" : "Orange Zone",
            "Palwal" : "Orange Zone",
            "Panchkula" : "Orange Zone",
            "Panipat" : "Orange Zone",
            "Rewari" : "Green Zone",
            "Rohtak" : "Orange Zone",
            "Sirsa" : "Orange Zone",
            "Sonipat" : "Red Zone",
            "Yamunanagar" : "Orange Zone"
        }
    },
    {
        "st_nm":"Himachal Pradesh",
        "st":"HimachalPradesh",
        "lat":"31.10002545",
        "long":"77.16659704",
        "zones" : {
            "Bilaspur" : "Green Zone",
            "Chamba" : "Orange Zone",
            "Hamirpur" : "Orange Zone",
            "Kangra" : "Orange Zone",
            "Kinnaur" : "Green Zone",
            "Kullu" : "Green Zone",
            "Lahul & Spiti" : "Green Zone",
            "Mandi" : "Green Zone",
            "Shimla" : "Green Zone",
            "Sirmaur" : "Orange Zone",
            "Solan" : "Orange Zone",
            "Una" : "Orange Zone"
        }
    },
    {
        "st_nm":"Jammu & Kashmir",
        "st":"JammuAndKashmir",
        "lat":"34.29995933",
        "long":"74.46665849",
        "zones" : {
            "Anantnag" : "Red Zone",
            "Bandipore" : "Red Zone",
            "Baramulla" : "Orange Zone",
            "Budgam" : "Orange Zone",
            "Doda" : "Green Zone",
            "Ganderbal" : "Orange Zone",
            "Jammu" : "Orange Zone",
            "Kargil" : "Orange Zone",
            "Kathua" : "Orange Zone",
            "Kishtwar" : "Green Zone",
            "Kulgam" : "Orange Zone",
            "Kupwara" : "Orange Zone",
            "Leh" : "Orange Zone",
            "Poonch" : "Green Zone",
            "Pulwama" : "Green Zone",
            "Rajouri" : "Orange Zone",
            "Ramban" : "Orange Zone",
            "Reasi" : "Orange Zone",
            "Samba" : "Orange Zone",
            "Shopian" : "Red Zone",
            "Srinagar" : "Red Zone",
            "Udhampur" : "Orange Zone"
        }
    },
    {
        "st_nm":"Jharkhand",
        "st":"Jharkhand",
        "lat":"23.80039349",
        "long":"86.41998572",
        "zones" : {
            "Bokaro" : "Orange Zone",
            "Chatra" : "Green Zone",
            "Deoghar" : "Orange Zone",
            "Dhanbad" : "Orange Zone",
            "Dumka" : "Green Zone",
            "Purbi Singhbhum" : "Green Zone",
            "Garhwa" : "Orange Zone",
            "Giridih" : "Orange Zone",
            "Godda" : "Green Zone",
            "Gumla" : "Green Zone",
            "Hazaribagh" : "Orange Zone",
            "Jamtara" : "Orange Zone",
            "Khunti" : "Green Zone",
            "Koderma" : "Orange Zone",
            "Latehar" : "Green Zone",
            "Lohardaga" : "Green Zone",
            "Pakur" : "Green Zone",
            "Palamu" : "Green Zone",
            "Ramgarh" : "Green Zone",
            "Ranchi" : "Red Zone",
            "Sahibganj" : "Green Zone",
            "Saraikela-kharsawan" : "Green Zone",
            "Simdega" : "Orange Zone",
            "Pashchimi Singhbhum" : "Green Zone"
        }
    },
    {
        "st_nm":"Karnataka",
        "st":"Karnataka",
        "lat":"12.57038129",
        "long":"76.91999711",
        "zones" : {
            "Bagalkot" : "Orange Zone",
            "Bellary" : "Orange Zone",
            "Belgaum" : "Orange Zone",
            "Bangalore Rural" : "Red Zone",
            "Bangalore Urban" : "Red Zone",
            "Bidar" : "Orange Zone",
            "Chamrajnagar" : "Green Zone",
            "Chikkaballapura" : "Orange Zone",
            "Chikmagalur" : "Green Zone",
            "Chitradurga" : "Green Zone",
            "Dakshina Kannada" : "Orange Zone",
            "Davangere" : "Green Zone",
            "Dharwad" : "Orange Zone",
            "Gadag" : "Orange Zone",
            "Hassan" : "Green Zone",
            "Haveri" : "Green Zone",
            "Gulbarga" : "Orange Zone",
            "Kodagu" : "Green Zone",
            "Kolar" : "Green Zone",
            "Koppal" : "Green Zone",
            "Mandya" : "Orange Zone",
            "Mysore" : "Red Zone",
            "Raichur" : "Green Zone",
            "Ramanagara" : "Green Zone",
            "Shimoga" : "Green Zone",
            "Tumkur" : "Orange Zone",
            "Udupi" : "Green Zone",
            "Uttara Kannada" : "Orange Zone",
            "Bijapur" : "Orange Zone",
            "Yadgir" : "Green Zone"
        }
    },
    {
        "st_nm":"Kerala",
        "st":"Kerala",
        "lat":"8.900372741",
        "long":"76.56999263",
        "zones" : {
            "Alappuzha" : "Orange Zone",
            "Ernakulam" : "Green Zone",
            "Idukki" : "Orange Zone",
            "Kannur" : "Red Zone",
            "Kasaragod" : "Orange Zone",
            "Kollam" : "Orange Zone",
            "Kottayam" : "Red Zone",
            "Kozhikode" : "Orange Zone",
            "Malappuram" : "Orange Zone",
            "Palakkad" : "Orange Zone",
            "Pathanamthitta" : "Orange Zone",
            "Thiruvananthapuram" : "Orange Zone",
            "Thrissur" : "Orange Zone",
            "Wayanad" : "Green Zone"
        }
    },
    {
        "st_nm":"Madhya Pradesh",
        "st":"MadhyaPradesh",
        "lat":"21.30039105",
        "long":"76.13001949",
        "zones" : {
            "Agar Malwa" : "Orange Zone",
            "Alirajpur" : "Orange Zone",
            "Anuppur" : "Green Zone",
            "Ashoknagar" : "Green Zone",
            "Balaghat" : "Green Zone",
            "Barwani" : "Red Zone",
            "Betul" : "Orange Zone",
            "Bhind" : "Green Zone",
            "Bhopal" : "Red Zone",
            "Burhanpur" : "Orange Zone",
            "Chhatarpur" : "Green Zone",
            "Chhindwara" : "Orange Zone",
            "Damoh" : "Green Zone",
            "Datia" : "Green Zone",
            "Dewas" : "Red Zone",
            "Dhar" : "Red Zone",
            "Dindori" : "Orange Zone",
            "Guna" : "Green Zone",
            "Gwalior" : "Red Zone",
            "Harda" : "Orange Zone",
            "Hoshangabad" : "Orange Zone",
            "Indore" : "Red Zone",
            "Jabalpur" : "Red Zone",
            "Jhabua" : "Green Zone",
            "Katni" : "Green Zone",
            // "Khandwa",
            "Khargone" : "Orange Zone",
            "Mandla" : "Green Zone",
            "Mandsaur" : "Orange Zone",
            "Morena" : "Orange Zone",
            "Neemuch" : "Green Zone",
            "Panna" : "Green Zone",
            "Narsinghpur" : "Green Zone",
            "Raisen" : "Orange Zone",
            "Rajgarh" : "Green Zone",
            "Ratlam" : "Orange Zone",
            "Rewa" : "Green Zone",
            "Sagar" : "Orange Zone",
            "Satna" : "Green Zone",
            "Sehore" : "Green Zone",
            "Seoni" : "Green Zone",
            "Shahdol" : "Orange Zone",
            "Shajapur" : "Orange Zone",
            "Sheopur" : "Orange Zone",
            "Shivpuri" : "Green Zone",
            "Sidhi" : "Green Zone",
            "Singrauli" : "Green Zone",
            "Tikamgarh" : "Orange Zone",
            "Ujjain" : "Red Zone",
            "Umaria" : "Green Zone",
            "Vidisha" : "Orange Zone"
        }
    },
    {
        "st_nm":"Maharashtra",
        "st":"Maharashtra",
        "lat":"19.25023195",
        "long":"73.16017493",
        "zones" : {
            "Ahmednagar": "Orange Zone",
            "Akola": "Red Zone",
            "Amravati": "Orange Zone",
            "Aurangabad": "Red Zone",
            "Beed": "Orange Zone",
            "Bhandara": "Orange Zone",
            "Buldhana": "Orange Zone",
            "Chandrapur": "Orange Zone",
            "Dhule": "Red Zone",
            "Gadchiroli" : "Green Zone",
            "Gondia" : "Green Zone",
            "Hingoli": "Orange Zone",
            "Jalgaon": "Red Zone",
            "Jalna": "Orange Zone",
            "Kolhapur": "Orange Zone",
            "Latur": "Orange Zone",
            "Mumbai": "Red Zone",
            "Mumbai Suburban": "Red Zone",
            "Nagpur": "Red Zone",
            "Nanded": "Orange Zone",
            "Nandurbar": "Orange Zone",
            "Nashik": "Red Zone",
            "Osmanabad" : "Green Zone",
            "Palghar": "Red Zone",
            "Parbhani": "Orange Zone",
            "Pune": "Red Zone",
            "Raigad": "Orange Zone",
            "Ratnagiri": "Orange Zone",
            "Sangli": "Orange Zone",
            "Satara": "Red Zone",
            "Sindhudurg" : "Green Zone",
            "Solapur": "Red Zone",
            "Thane": "Red Zone",
            "Wardha" : "Green Zone",
            "Washim" : "Green Zone",
            "Yavatmal": "Red Zone"
        }
    },
    {
        "st_nm":"Manipur",
        "st":"Manipur",
        "lat":"24.79997072",
        "long":"93.95001705",
        "zones" : {
            "Bishnupur" : "Green Zone",
            "Chandel" : "Green Zone",
            "Churachandpur" : "Green Zone",
            "Imphal East" : "Green Zone",
            "Imphal West" : "Green Zone",
            "Jiribam" : "Green Zone",
            "Kakching" : "Green Zone",
            "Kamjong" : "Green Zone",
            "Kangpokpi" : "Green Zone",
            "Noney" : "Green Zone",
            "Pherzawl" : "Green Zone",
            "Senapati" : "Green Zone",
            "Tamenglong" : "Green Zone",
            "Tengnoupal" : "Green Zone",
            "Thoubal" : "Green Zone",
            "Ukhrul" : "Green Zone"

        }
    },
    {
        "st_nm":"Meghalaya",
        "st":"Meghalaya",
        "lat":"25.57049217",
        "long":"91.8800142",
        "zones" : {
            "East Garo Hills" : "Green Zone",
            "East Jaintia Hills" : "Green Zone",
            "East Khasi Hills" : "Orange Zone",
            "North Garo Hills" : "Green Zone",
            "Ri Bhoi" : "Green Zone",
            "South Garo Hills" : "Green Zone",
            "South West Garo Hills" : "Green Zone",
            "South West Khasi Hills" : "Green Zone",
            "West Garo Hills" : "Green Zone",
            "Jaintia Hills" : "Green Zone",
            "West Khasi Hills" : "Green Zone"
        }
    },
    {
        "st_nm":"Mizoram",
        "st":"Mizoram",
        "lat":"23.71039899",
        "long":"92.72001461",
        "zones" : {
            "Aizawl" : "Green Zone",
            "Champhai" : "Green Zone",
            "Kolasib" : "Green Zone",
            "Lawangtlai" : "Green Zone",
            "Lunglei" : "Green Zone",
            "Mamit" : "Green Zone",
            "Saiha" : "Green Zone",
            "Serchhip" : "Green Zone"
        }
    },
    {
        "st_nm":"Nagaland",
        "st":"Nagaland",
        "lat":"25.6669979",
        "long":"94.11657019",
        "zones" : {
            "Dimapur" : "Green Zone",
            "Kiphire" : "Green Zone",
            "Kohima" : "Green Zone",
            "Longleng" : "Green Zone",
            "Mokokchung" : "Green Zone",
            "Mon" : "Green Zone",
            "Peren" : "Green Zone",
            "Phek" : "Green Zone",
            "Tuensang" : "Green Zone",
            "Wokha" : "Green Zone",
            "Zunheboto" : "Green Zone"
        }
    },
    {
        "st_nm":"Odisha",
        "st":"Odisha",
        "lat":"19.82042971",
        "long":"85.90001746",
        "zones" : {
            "Angul" : "Green Zone",
            "Balangir" : "Green Zone",
            "Balasore" : "Red Zone",
            "Bargarh" : "Green Zone",
            "Bhadrak" : "Red Zone",
            "Boudh" : "Green Zone",
            "Cuttack" : "Green Zone",
            "Deogarh" : "Green Zone",
            "Dhenkanal" : "Orange Zone",
            "Gajapati" : "Green Zone",
            "Ganjam" : "Green Zone",
            "Jagatsinghapur" : "Green Zone",
            "Jajapur" : "Red Zone",
            "Jharsuguda" : "Green Zone",
            "Kalahandi" : "Orange Zone",
            "Kandhamal" : "Green Zone",
            "Kendrapara" : "Orange Zone",
            "Kendujhar" : "Green Zone",
            "Khordha" : "Orange Zone",
            "Koraput" : "Orange Zone",
            "Malkangiri" : "Green Zone",
            "Mayurbhanj" : "Green Zone",
            "Nabarangpur" : "Green Zone",
            "Nayagarh" : "Green Zone",
            "Nuapada" : "Green Zone",
            "Puri" : "Green Zone",
            "Rayagada" : "Green Zone",
            "Sambalpur" : "Green Zone",
            "Sonepur" : "Green Zone",
            "Sundargarh" : "Orange Zone"
        }
    },
    {
        "st_nm":"Punjab",
        "st":"Punjab",
        "lat":"31.51997398",
        "long":"75.98000281",
        "zones" : {
            "Amritsar" : "Orange Zone",
            "Barnala" : "Orange Zone",
            "Bathinda" : "Green Zone",
            "Faridkot" : "Orange Zone",
            "Fatehgarh Sahib" : "Green Zone",
            "Fazilka" : "Green Zone",
            "Firozpur" : "Orange Zone",
            "Gurdaspur" : "Orange Zone",
            "Hoshiarpur" : "Orange Zone",
            "Jalandhar" : "Red Zone",
            "Kapurthala" : "Orange Zone",
            "Ludhiana" : "Red Zone",
            "Mansa" : "Orange Zone",
            "Moga" : "Orange Zone",
            "Muktsar" : "Orange Zone",
            "Shahid Bhagat Singh Nagar" : "Orange Zone",
            "Pathankot" : "Orange Zone",
            "Patiala" : "Red Zone",
            "Rupnagar" : "Green Zone",
            "Sahibzada Ajit Singh Nagar" : "Orange Zone",
            "Sangrur" : "Orange Zone",
            "Tarn Taran" : "Orange Zone"
        }
    },
    {
        "st_nm":"Rajasthan",
        "st":"Rajasthan",
        "lat":"26.44999921",
        "long":"74.63998124",
        "zones" : {
            "Ajmer" : "Red Zone",
            "Alwar" : "Orange Zone",
            "Banswara" : "Red Zone",
            "Baran" : "Green Zone",
            "Barmer" : "Orange Zone",
            "Bharatpur" : "Red Zone",
            "Bhilwara" : "Orange Zone",
            "Bikaner" : "Orange Zone",
            "Bundi" : "Green Zone",
            "Chittorgarh" : "Orange Zone",
            "Churu" : "Orange Zone",
            "Dausa" : "Orange Zone",
            "Dholpur" : "Orange Zone",
            "Dungarpur" : "Orange Zone",
            "Ganganagar" : "Green Zone",
            "Hanumangarh" : "Orange Zone",
            "Jaipur" : "Red Zone",
            "Jaisalmer" : "Orange Zone",
            "Jalore" : "Green Zone",
            "Jhalawar" : "Red Zone",
            "Jhunjhunu" : "Orange Zone",
            "Jodhpur" : "Red Zone",
            "Karauli" : "Orange Zone",
            "Kota" : "Red Zone",
            "Nagaur" : "Red Zone",
            "Pali" : "Orange Zone",
            "Pratapgarh" : "Green Zone",
            "Rajsamand" : "Orange Zone",
            "Sawai Madhopur" : "Orange Zone",
            "Sikar" : "Orange Zone",
            "Sirohi" : "Green Zone",
            "Tonk" : "Orange Zone",
            "Udaipur" : "Orange Zone"
        }
    },
    {
        "st_nm":"Sikkim",
        "st":"Sikkim",
        "lat":"27.3333303",
        "long":"88.6166475",
        "zones" : {
            "East" : "Green Zone",
            "North" : "Green Zone",
            "South" : "Green Zone",
            "West" : "Green Zone"
        }
    },
    {
        "st_nm":"Tamil Nadu",
        "st":"TamilNadu",
        "lat":"12.92038576",
        "long":"79.15004187",
        "zones" : {
            "Ariyalur" : "Orange Zone",
            "Chennai" : "Red Zone",
            "Coimbatore" : "Orange Zone",
            "Cuddalore" : "Orange Zone",
            "Dharmapuri" : "Orange Zone",
            "Dindigul" : "Orange Zone",
            "Erode" : "Orange Zone",
            "Kancheepuram" : "Red Zone",
            "Kanniyakumari" : "Orange Zone",
            "Karur" : "Orange Zone",
            "Krishnagiri" : "Green Zone",
            "Madurai" : "Red Zone",
            "Nagappattinam" : "Orange Zone",
            "Namakkal" : "Red Zone",
            "The Nilgiris" : "Orange Zone",
            "Perambalur" : "Orange Zone",
            "Pudukkottai" : "Orange Zone",
            "Ramanathapuram" : "Orange Zone",
            "Salem" : "Orange Zone",
            "Sivaganga" : "Orange Zone",
            "Thanjavur" : "Red Zone",
            "Theni" : "Orange Zone",
            "Thoothukkudi" : "Orange Zone",
            "Tiruchirappalli" : "Orange Zone",
            "Tirunelveli" : "Orange Zone",
            "Tiruppur" : "Red Zone",
            "Thiruvallur" : "Red Zone",
            "Tiruvannamalai" : "Orange Zone",
            "Thiruvarur" : "Red Zone",
            "Vellore" : "Red Zone",
            "Viluppuram" : "Orange Zone",
            "Virudunagar" : "Red Zone"
        }
    },
    {
        "st_nm":"Telangana",
        "st":"Telangana",
        "lat":"18.1124",
        "long":"79.0193",
        "zones" : {
            "Adilabad" : "Orange Zone",
            "Bhadradri Kothagudem" : "Green Zone",
            "Hyderabad" : "Red Zone",
            "Jagtial" : "Orange Zone",
            "Jangaon" : "Orange Zone",
            "Jayashankar Bhupalpally" : "Orange Zone",
            "Jogulamba Gadwal" : "Orange Zone",
            "Kamareddy" : "Orange Zone",
            "Karimnagar" : "Orange Zone",
            "Khammam" : "Orange Zone",
            "Kumurambheem Asifabad" : "Orange Zone",
            "Mahabubabad" : "Green Zone",
            "Mahabubnagar" : "Orange Zone",
            "Mancherial" : "Orange Zone",
            "Medak" : "Orange Zone",
            "Medchal" : "Red Zone",
            "Nagarkurnool" : "Green Zone",
            "Nalgonda" : "Orange Zone",
            "Nirmal" : "Orange Zone",
            "Nizamabad" : "Orange Zone",
            "Peddapalli" : "Green Zone",
            "Rajanna Sircilla" : "Orange Zone",
            "Rangareddy" : "Red Zone",
            "Sangareddy" : "Orange Zone",
            "Siddipet" : "Green Zone",
            "Suryapet" : "Red Zone",
            "Vikarabad" : "Red Zone",
            "Wanaparthy" : "Green Zone",
            "Warangal Rural" : "Green Zone",
            "Warangal Urban" : "Red Zone",
            "Yadadri Bhuvanagiri" : "Green Zone"
        }
    },
    {
        "st_nm":"Tripura",
        "st":"Tripura",
        "lat":"23.83540428",
        "long":"91.27999914",
        "zones" : {
            "Dhalai" : "Green Zone",
            // "Gomati" : "Orange Zone",
            // "Khowai" : "Green Zone",
            "North Tripura" : "Orange Zone",
            // "Sepahijala" : "Green Zone",
            "South Tripura" : "Green Zone",
            // "Unakoti" : "Green Zone",
            "West Tripura" : "Green Zone"
        }
    },
    {
        "st_nm":"Uttarakhand",
        "st":"Uttarakhand",
        "lat":"30.0668",
        "long":"79.0193",
        "zones" : {
            "Almora" : "Green Zone",
            "Bageshwar" : "Green Zone",
            "Chamoli" : "Green Zone",
            "Champawat" : "Green Zone",
            "Dehradun" : "Orange Zone",
            "Haridwar" : "Red Zone",
            "Nainital" : "Orange Zone",
            "Pauri Garhwal" : "Green Zone",
            "Pithoragarh" : "Green Zone",
            "Rudraprayag" : "Green Zone",
            "Tehri Garhwal" : "Green Zone",
            "Udham Singh Nagar" : "Green Zone",
            "Uttarkashi" : "Green Zone"
        }
    },
    {
        "st_nm":"Uttar Pradesh",
        "st":"UttarPradesh",
        "lat":"27.59998069",
        "long":"78.05000565",
        "zones" : {
            "Agra" : "Red Zone",
            "Aligarh" : "Red Zone",
            "Prayagraj" : "Orange Zone",
            "Ambedkar Nagar" : "Green Zone",
            "Amethi (Chatrapati Sahuji Mahraj Nagar)" : "Green Zone",
            "Amroha (J.P. Nagar)" : "Red Zone",
            "Auraiya" : "Orange Zone",
            "Azamgarh" : "Orange Zone",
            "Baghpat" : "Orange Zone",
            "Bahraich" : "Orange Zone",
            "Ballia" : "Green Zone",
            "Balrampur" : "Orange Zone",
            "Banda" : "Orange Zone",
            "Barabanki" : "Green Zone",
            "Bareilly" : "Red Zone",
            "Basti" : "Orange Zone",
            "Bhadohi" : "Orange Zone",
            "Bijnor" : "Red Zone",
            "Budaun" : "Orange Zone",
            "Bulandshahr" : "Red Zone",
            "Chandauli" : "Green Zone",
            "Chitrakoot" : "Green Zone",
            "Deoria" : "Green Zone",
            "Etah" : "Orange Zone",
            "Etawah" : "Orange Zone",
            "Ayodhya " : "Orange Zone",
            "Farrukhabad" : "Green Zone",
            "Fatehpur" : "Green Zone",
            "Firozabad" : "Red Zone",
            "Gautam Buddha Nagar" : "Red Zone",
            "Ghaziabad" : "Orange Zone",
            "Ghazipur" : "Orange Zone",
            "Gonda" : "Orange Zone",
            "Gorakhpur" : "Orange Zone",
            "Hamirpur" : "Green Zone",
            "Hapur (Panchsheel Nagar)" : "Orange Zone",
            "Hardoi" : "Orange Zone",
            "Hathras" : "Green Zone",
            "Jalaun" : "Orange Zone",
            "Jaunpur" : "Orange Zone",
            "Jhansi" : "Orange Zone",
            "Kannauj" : "Orange Zone",
            "Kanpur Dehat" : "Green Zone",
            "Kanpur Nagar" : "Red Zone",
            "Kanshiram Nagar (Kasganj)" : "Orange Zone",
            "Kaushambi" : "Orange Zone",
            "Kushinagar (Padrauna)" : "Green Zone",
            "Lakhimpur - Kheri" : "Green Zone",
            "Lalitpur" : "Green Zone",
            "Lucknow" : "Red Zone",
            "Maharajganj" : "Green Zone",
            "Mahoba" : "Green Zone",
            "Mainpuri" : "Orange Zone",
            "Mathura" : "Red Zone",
            "Mau" : "Orange Zone",
            "Meerut" : "Red Zone",
            "Mirzapur" : "Orange Zone",
            "Moradabad" : "Red Zone",
            "Muzaffarnagar" : "Red Zone",
            "Pilibhit" : "Orange Zone",
            "Pratapgarh" : "Orange Zone",
            "Rae Bareli" : "Red Zone",
            "Rampur" : "Red Zone",
            "Saharanpur" : "Red Zone",
            "Sambhal (Bhim Nagar)" : "Orange Zone",
            "Sant Kabir Nagar" : "Red Zone",
            "Shahjahanpur" : "Green Zone",
            "Shamali (Prabuddh Nagar)" : "Orange Zone",
            "Shravasti" : "Orange Zone",
            "Siddharth Nagar" : "Green Zone",
            "Sitapur" : "Orange Zone",
            "Sonbhadra" : "Green Zone",
            "Sultanpur" : "Orange Zone",
            "Unnao" : "Orange Zone",
            "Varanasi" : "Red Zone"
        }
    },
    {
        "st_nm":"West Bengal",
        "st":"WestBengal",
        "lat":"22.58039044",
        "long":"88.32994665",
        "zones" : {
            "Alipurduar" : "Green Zone",
            "Bankura" : "Green Zone",
            "Birbhum" : "Green Zone",
            "Barddhaman" : "Orange Zone",
            "Koch Bihar" : "Green Zone",
            "Dakshin Dinajpur" : "Green Zone",
            "Darjiling" : "Red Zone",
            "Hooghly" : "Orange Zone",
            "Howrah" : "Red Zone",
            "Haora" : "Green Zone",
            "Jalpaiguri" : "Red Zone",
            "Kalimpong" : "Red Zone",
            "Kolkata" : "Red Zone",
            "Maldah" : "Red Zone",
            "Murshidabad" : "Orange Zone",
            "Nadia" : "Orange Zone",
            "North 24 Parganas" : "Red Zone",
            "Pashchim Medinipur" : "Red Zone",
            "Purba Medinipur" : "Red Zone",
            "Puruliya" : "Green Zone",
            "South 24 Parganas" : "Red Zone",
            "Uttar Dinajpur" : "Green Zone"
        }
    },
    {
        "st_nm":"Andaman & Nicobar Island",
        "st":"AndamanAndNicobar",
        "lat":"11.66702557",
        "long":"92.73598262",
        "zones" : {
            "South Andamans": "Red Zone",
            "Nicobars" : "Green Zone",
            "North & Middle Andaman" : "Green Zone"
        }
    },
    {
        "st_nm":"Chandigarh",
        "st":"Chandigarh",
        "lat":"30.71999697",
        "long":"76.78000565",
        "zones" : {
            "Chandigarh" : "Red Zone"
        }
    },
    {
        "st_nm":"Dadara & Nagar Haveli",
        "st":"DadarNagarHaveli",
        "lat":"20.26657819",
        "long":"73.0166178",
        "zones" : {
            "Dadra & Nagar Haveli" : "Green Zone"
        }
    },
    {
        "st_nm":"Daman & Diu",
        "st":"DamanDiu",
        "lat":"20.4283",
        "long":"72.8397",
        "zones" : {
            "Daman" : "Green Zone",
            "Diu" : "Green Zone"
        }
    },
    {
        "st_nm":"Delhi",
        "st":"Delhi",
        "lat":"28.6699929",
        "long":"77.23000403",
        "zones" : {
            "Central": "Red Zone",
            "East": "Red Zone",
            "New Delhi": "Red Zone",
            "North": "Red Zone",
            "North East": "Red Zone",
            "North West": "Red Zone",
            // "Shahdara": "Red Zone",
            "South": "Red Zone",
            // "South East" : "Red Zone",
            "South West": "Red Zone",
            "West": "Red Zone"
        }
    },
    {
        "st_nm":"Lakshadweep",
        "st":"Lakshadweep",
        "lat":"10.56257331",
        "long":"72.63686717",
        "zones" : {
            "Lakshadweep" : "Green Zone"
        }
    },
    {
        "st_nm":"Puducherry",
        "st":"Puducherry",
        "lat":"11.93499371",
        "long":"79.83000037",
        "zones" : {
            "Karaikal" : "Green Zone",
            "Mahe" : "Green Zone",
            "Pondicherry" : "Orange Zone",
            "Yanam" : "Green Zone"
        }
    }];

module.exports = states;